export const ActionTypes = {
  FETCH_INGREDIENT: "FETCH_INGREDIENT",
  SET_INGREDIENT: "SET_INGREDIENT",
  SELECTED_INGREDIENT: "SELECTED_INGREDIENT",
  REMOVE_SELECTED_INGREDIENT: "REMOVE_SELECTED_INGREDIENT",
}